### ISSUE TITLE
Crash on start of watchBackend()

### ISSUE THREAD

**Issue by ygersie** [fabiolb/fabio#650]
this commit https://github.com/fabiolb/fabio/commit/bdc036420bfc6df8613a95bcd7d3c29b82c3065a changed the `next` bytes.Buffer to a pointer. The first time `Reset()` is called while this is still a nil pointer Fabio crashes:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1607a5d]

goroutine 31 [running]:
bytes.(*Buffer).Reset(...)
	/usr/local/Cellar/go/1.11/libexec/src/bytes/buffer.go:99
main.watchBackend(0xc000232000, 0xc0001cc8a0)
	/Users/ygersie/gopath/src/github.com/fabiolb/fabio/main.go:465 +0x20d
created by main.main
	/Users/ygersie/gopath/src/github.com/fabiolb/fabio/main.go:134 +0x78a
```

**Comment by leprechau** [comment]
Thanks I’ll fix this today.

-- Aaron
