### ISSUE TITLE
Fabio crashes with a specific path of vault kv for certificates

### ISSUE THREAD

**Issue by jtbjid** [fabiolb/fabio#672]
Hello,

I'm encountering a crash with fabio using vault kv as a certificate store.

Here is the output of the crash 
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x852b1b4]

goroutine 58 [running]:
github.com/fabiolb/fabio/cert.(*VaultSource).load.func1(0x933e010, 0x10, 0x868c185, 0x4, 0x0, 0x0)
	/Users/frank/src/github.com/fabiolb/fabio/cert/vault_source.go:53 +0x24
github.com/fabiolb/fabio/cert.(*VaultSource).load(0x90f0ab0, 0x911ef60, 0xb, 0x90efd00, 0x0, 0x0)
	/Users/frank/src/github.com/fabiolb/fabio/cert/vault_source.go:120 +0x4d3
github.com/fabiolb/fabio/cert.(*VaultSource).load-fm(0x911ef60, 0xb, 0x0, 0x0, 0x0)
	/Users/frank/src/github.com/fabiolb/fabio/cert/vault_source.go:35 +0x30
github.com/fabiolb/fabio/cert.watch(0x90ed980, 0xb2d05e00, 0x0, 0x911ef60, 0xb, 0x90f3a98)
	/Users/frank/src/github.com/fabiolb/fabio/cert/watch.go:21 +0x8a
created by github.com/fabiolb/fabio/cert.(*VaultSource).Certificates
	/Users/frank/src/github.com/fabiolb/fabio/cert/vault_source.go:40 +0xa0`

Here is the configuration that makes it crash

`proxy.cs = cs=*.app.domain.eu;type=vault;cert=secret/ssl/
proxy.addr = :443;cs=*.app.domain.eu,:80
proxy.cs = cs=*.app.domain.io;type=vault;cert=secret/ssl/
proxy.addr = :443;cs=*.app.domain.io,:80`

If certificate are stored in another ( like `secret/fabio/ssl` for example), it's working well.
If I mix path between the 2 certificates as followed, it also works

`proxy.cs = cs=*.app.domain.io;type=vault;cert=secret/ssl/
proxy.addr = :443;cs=*.app.domain.io,:80
proxy.cs = cs=*.app.domain.eu;type=vault;cert=secret/fabio/ssl/
proxy.addr = :443;cs=*.app.domain.eu,:80`

But if I interchange the order of the certificate definition as followed, it crashes

`proxy.cs = cs=*.app.domain.eu;type=vault;cert=secret/fabio/ssl/
proxy.addr = :443;cs=*.app.domain.eu,:80
proxy.cs = cs=*.app.domain.io;type=vault;cert=secret/ssl/
proxy.addr = :443;cs=*.app.domain.io,:80`

Thinking it's because of the path name ( `secret/ssl/` ), but I'd like to know if it's something different.

Thank you

**Comment by pschultz** [comment]
You are probably storing the certificate incorrectly in secret/ssl/<hostname>. Obviously fabio shouldn't crash when that happens, but to understand how to fix this properly I need a bit more information.

What is the output of the following commands?

    $ vault read sys/internal/ui/mounts/secret/ssl/
    $ vault read -format=json secret/ssl/<hostname>
    $ vault read -format=json secret/data/ssl/<hostname>
